//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekUAS_Kelompok3
{
    using System;
    using System.Collections.Generic;
    
    public partial class alat_musik
    {
        public int Id { get; set; }
        public string program_kelas { get; set; }
        public string iuran { get; set; }
        public string durasi { get; set; }
        public string keterangan { get; set; }
    }
}
