//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekUAS_Kelompok3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class uasbadEntities1 : DbContext
    {
        public uasbadEntities1()
            : base("name=uasbadEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alat_musik> alat_musik { get; set; }
        public virtual DbSet<pembayaran> pembayarans { get; set; }
        public virtual DbSet<pendaftaran> pendaftarans { get; set; }
        public virtual DbSet<testi> testis { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
