//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekUAS_Kelompok3
{
    using System;
    using System.Collections.Generic;
    
    public partial class pembayaran
    {
        public int Id { get; set; }
        public string username { get; set; }
        public string pk { get; set; }
        public string bulan { get; set; }
        public Nullable<double> total { get; set; }
        public string status { get; set; }
        public string iuran { get; set; }
        public string nama { get; set; }
    }
}
