//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekUAS_Kelompok3
{
    using System;
    using System.Collections.Generic;
    
    public partial class pendaftaran
    {
        public int Id { get; set; }
        public string nama { get; set; }
        public string tanggal { get; set; }
        public string jeniskelamin { get; set; }
        public string nohp { get; set; }
        public string pk { get; set; }
        public string hari { get; set; }
        public string tipe { get; set; }
        public string username { get; set; }
    }
}
