//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekUAS_Kelompok3
{
    using System;
    using System.Collections.Generic;
    
    public partial class testi
    {
        public int Id { get; set; }
        public string ulasan { get; set; }
        public string sk { get; set; }
        public string username { get; set; }
    }
}
